services:

  registry-basic:
    image: registry
    ports:
      - 5001:5001
    volumes:
      - type: bind
        source: ./auth.htpasswd
        target: /etc/docker/registry/auth.htpasswd
      - ./data:/var/lib/registry/
      - ./certs:/certs
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5001
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/registry.key
      - 'REGISTRY_AUTH={htpasswd: {realm: 127.0.0.1, path: /etc/docker/registry/auth.htpasswd}}'

  registry:
    image: registry
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./auth.htpasswd
        target: /etc/docker/registry/auth.htpasswd
      - ./data:/var/lib/registry/
      - ./certs:/certs
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/registry.key
      - 'REGISTRY_AUTH={htpasswd: {realm: 127.0.0.1, path: /etc/docker/registry/auth.htpasswd}}'

  index-server:
    image: nginx:alpine
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./indexes:/srv
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf

  redis:
    image: redis
    ports:
      - 6379:6379

  proxy: 
    #image: loresuso/go-proxy
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile-oauth-proxy
    network_mode: "host"

  oauth:
    #image: loresuso/go-oauth
    build:
      context: .
      dockerfile: Dockerfile-oauth-server
    ports:
      - 9096:9096
